### ISSUE TITLE
Uncaught Promise

### ISSUE THREAD

**Issue by rrawann** [alferjay/odoo-owl-tutorial#4]
When i use this ==== > 
.then(function (datas) {
          if (initial_render) {
            this.$(".filter_view_tb").html(
              QWeb.render("GLFilterView3", {
                filter_data: datas["filters"],
              })
            );
            this.$el.find(".employees").select2({
              placeholder: "Employees...",
            });
          }

i got an error Uncaught Promise > this.$ is not a function
how can i use  this.$ on owl framework?

**Comment by alferjay** [comment]
Sorry for my late reply. You can merge jquery code in OWL. But you need to add it in onMounted life cycle method. Check the link below on how to implement it.

https://youtu.be/FZzUVgL9hMQ

**Comment by rrawann** [comment]
Thanks @alferjay
